/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_romide_terminal_jni_KivaTerminal */

#ifndef _Included_com_romide_terminal_jni_KivaTerminal
#define _Included_com_romide_terminal_jni_KivaTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_romide_terminal_jni_KivaTerminal
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_romide_terminal_jni_KivaTerminal_setenv
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
